### PR TITLE
Fix installation on x64

### LINKED ISSUE #4: rclone not found on WSA (Android 11 x64)
```
redfin:/ $ su
redfin:/ # rclone config
Using 'rclone' binary: /dev/wsa-magisk/.magisk/modules/rclone.mount/rclone
/system/bin/rclone[130]: /dev/wsa-magisk/.magisk/modules/rclone.mount/rclone: inaccessible or not found
```

This comes up when I run rclone config. And indeed it does not exist there:

```
redfin:/ # ls /dev/wsa-magisk/.magisk/modules/rclone.mount/
CHANGELOG.md  module.prop  service.sh  syncd.sh  system  uninstall.sh
```
when I search for rclone this comes up:

```
redfin:/ # find / -name "rclone" -type f
/dev/wsa-magisk/.magisk/modules/rclone.mount/system/bin/rclone
find: '/dev/wsa-magisk/.magisk/mirror/system_root': loop detected
/dev/wsa-magisk/.magisk/mirror/data/adb/modules/rclone.mount/system/bin/rclone
/system/bin/rclone
/data/adb/modules/rclone.mount/system/bin/rclone
```
and none of them work.

Am I doing something wrong?

### PR DESCRIPTION
**Pull request by yujincheng08**
Fix #4

### CODE REVIEW

**Comment by AvinashReddy3108** [comment]
Let me make a quick test ZIP with this change...

**Comment by AvinashReddy3108** [comment]
@yujincheng08 @Auncaughbove17
Please test this ZIP in your WSA setup and let me know if it works?
https://stash.avinashreddy3108.workers.dev/0:/rclone-mount-magisk-PR5.zip

Had to upload it somewhere, because for some reason "Releases" could not take my file.

**Comment by Alistair1231** [comment]
@AvinashReddy3108  It starts now! Thanks!

```
PS C:\Users\user\Downloads> adb shell
redfin:/ $ su
redfin:/ # rclone config
Using 'rclone' binary: /dev/wsa-magisk/.magisk/modules/rclone.mount/rclone
2021/12/01 16:58:53 NOTICE: Config file "/.rclone.conf" not found - using defaults
No remotes found - make a new one
n) New remote
s) Set configuration password
q) Quit config
n/s/q>
```

**Comment by AvinashReddy3108** [comment]
Awesome, will merge this fix along with some more stuff

**Comment by Alistair1231** [comment]
It seems to have issues creating a config however. I don't know if this is related:

```
y) Yes this is OK (default)
e) Edit this remote
d) Delete this remote
y/e/d>
2021/12/01 17:03:23 ERROR : Failed to save config after 10 tries: Failed to create temp file for new config: open /.rclone.conf550278168: read-only file system
Current remotes:

Name                 Type
====                 ====
dav                  webdav

e) Edit existing remote
n) New remote
d) Delete remote
r) Rename remote
c) Copy remote
s) Set configuration password
q) Quit config
e/n/d/r/c/s/q> q

130|redfin:/ # rclone config
Using 'rclone' binary: /dev/wsa-magisk/.magisk/modules/rclone.mount/rclone
2021/12/01 17:06:49 NOTICE: Config file "/.rclone.conf" not found - using defaults
No remotes found - make a new one
n) New remote
s) Set configuration password
q) Quit config
n/s/q>
```
I created a config file on my PC now and copied it to `/sdcard/.rclone/rclone.conf` like it says in README.md but it doesn't recognize it either:

```
redfin:/storage/emulated/0/.rclone # ls /sdcard/.rclone/
rclone.conf  rclone.log
redfin:/storage/emulated/0/.rclone # cat /sdcard/.rclone/r
rclone.conf  rclone.log
redfin:/storage/emulated/0/.rclone # cat /sdcard/.rclone/rclone.log
2021/12/01 17:11:42 NOTICE: webdav root '': --vfs-cache-mode writes or full is recommended for this remote as it can't stream
redfin:/storage/emulated/0/.rclone # cat /sdcard/.rclone/rclone.conf
[dav]
type = webdav
url = https://website.com/dav/
vendor = other
user = AAAAAA
pass = AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
redfin:/storage/emulated/0/.rclone # rclone config
Using 'rclone' binary: /dev/wsa-magisk/.magisk/modules/rclone.mount/rclone
2021/12/01 17:12:40 NOTICE: Config file "/.rclone.conf" not found - using defaults
No remotes found - make a new one
n) New remote
s) Set configuration password
q) Quit config
n/s/q>
```

**Comment by AvinashReddy3108** [comment]
> It seems to have issues creating a config however. I don't know if this is related:
> 
> ```
> y) Yes this is OK (default)
> e) Edit this remote
> d) Delete this remote
> y/e/d>
> 2021/12/01 17:03:23 ERROR : Failed to save config after 10 tries: Failed to create temp file for new config: open /.rclone.conf550278168: read-only file system
> Current remotes:
> 
> Name                 Type
> ====                 ====
> dav                  webdav
> 
> e) Edit existing remote
> n) New remote
> d) Delete remote
> r) Rename remote
> c) Copy remote
> s) Set configuration password
> q) Quit config
> e/n/d/r/c/s/q> q
> 
> 130|redfin:/ # rclone config
> Using 'rclone' binary: /dev/wsa-magisk/.magisk/modules/rclone.mount/rclone
> 2021/12/01 17:06:49 NOTICE: Config file "/.rclone.conf" not found - using defaults
> No remotes found - make a new one
> n) New remote
> s) Set configuration password
> q) Quit config
> n/s/q>
> ```

Please open a new issue for this, we'll continue working on it over there.

**Comment by lubo99** [comment]
hi folks. was this fixed?

**Comment by AvinashReddy3108** [comment]
> hi folks. was this fixed?

Yes.
Also, I'll suggest you try this fork: https://github.com/Howard20181/rclone-mount-magisk
It's more up-to-date

**Comment by lubo99** [comment]
so i should uninstal your module and install this one instead of it? i dont want to use http but rather samba

this is what i get when i try to run rclone config after reboot and instal module you provided link to

 # cd /debug_ramdisk/.magisk/modules/rclone.mount                                                          
/system/bin/sh: cd: /debug_ramdisk/.magisk/modules/rclone.mount: No such file or directory  and really such directory as this does not exist in my phone **rclone.mount**

**Comment by AvinashReddy3108** [comment]
> so i should uninstal your module and install this one instead of it?

Yes.

**Comment by lubo99** [comment]
Hmm. Stil samé problem /system/bin/rclone[135]: /debug_ramdisk/.magisk/modules/rclone.mount/rclone: inaccessible or not found

**Comment by AvinashReddy3108** [comment]
Must be a $PATH issue either from newer Android or newer Magisk versions..

I'm kind of out of touch with this stuff, will need some catching up to do.

**Comment by lubo99** [comment]
Yes it wants to run rclone from directory which does not exist. When i provide full path in command line it opens config. What should be mount command to mount usb hardrive connected to router who propagates it AS samba drive.   /Volumes/共享/video is Network path.
this is what i created

:/.config/rclone # cat rclone.conf
[router]
type = smb
host = 192.168.31.1
user = anonymous

now trying to mount it:


**data/adb/modules/rclone.mount/rclone mount /**/smb/192.168.31.1/Volumes/共享/video

Command mount needs 2 arguments minimum: you provided 1 non flag arguments: ["//smb/192.168.31.1/Volumes/共享/video


any idea ?

**Comment by lubo99** [comment]
Hi mate any update on this?


Dňa ne 29. 10. 2023, 14:29 Avinash Reddy ***@***.***>K

Dňa ne 29. 10. 2023, 14:29 Avinash Reddy ***@***.***>
napísal(a):

> Must be a $PATH issue either from newer Android or newer Magisk versions..
>
> I'm kind of out of touch with this stuff, will need some catching up to
> do.
>

**Pull request merged**
